@startuml
!include ../templates/C4_Component.puml

SHOW_PERSON_OUTLINE()

Person(user, "UI(Пользователь)")

System_Ext(gateway, "API Gateway")
System_Ext(tensor, "Temperature tensor")

System_Boundary(devicesMicroservice, "Микросервис управления устройствами") {
    Container(devices, "smart-home-devices")
}

System_Boundary(telemetryMicroservice, "Микросервис мониторинга устройств") {
    Container(telemetry, "smart-home-telemetry")
}

ContainerQueue(kafka, "Kafka", $techn="температуры с датчиков")

Rel(user, gateway, "Взаимодействие с API приложения")
Rel(gateway, devices, "Включить/выключить подсистему отопления")
Rel(gateway, devices, "Установить желаемую температуру в подсистеме отопления")
Rel(gateway, telemetry, "Посмотреть текущую температуру в подсистеме отопления")

Rel(kafka, telemetry, "Чтение температур с датчиков")
Rel(tensor, kafka, "Публикация температуры")

SHOW_LEGEND()

@enduml